version: '3.8'

services:
  redis:
    image: redis
    ports:
      - "6379:6379"

  config-server:
    build: ./config-server
    ports:
      - "8888:8888"
    networks:
      - ecommerce-net

  eureka-server:
    build: ./eureka-server
    ports:
      - "8761:8761"
    networks:
      - ecommerce-net

  api-gateway:
    build: ./api-gateway
    ports:
      - "8080:8080"
    depends_on:
      - config-server
      - eureka-server
    environment:
      EUREKA_HOST: eureka-server
      CONFIG_SERVER_HOST: config-server
    networks:
      - ecommerce-net

  auth-service:
    build: ./auth-service
    ports:
      - "8081:8081"
    depends_on:
      - config-server
      - eureka-server
    environment:
      EUREKA_HOST: eureka-server
      CONFIG_SERVER_HOST: config-server
      SPRING_DATASOURCE_URL: jdbc:mysql://host.docker.internal:3306/user_auth_db
      SPRING_DATASOURCE_USERNAME: root
      SPRING_DATASOURCE_PASSWORD: MySQL%4243
    networks:
      - ecommerce-net

  user:
    build: ./user
    ports:
      - "8082:8082"
    depends_on:
      - config-server
      - eureka-server
    environment:
      EUREKA_HOST: eureka-server
      CONFIG_SERVER_HOST: config-server
      SPRING_DATASOURCE_URL: jdbc:mysql://host.docker.internal:3306/user_db
      SPRING_DATASOURCE_USERNAME: root
      SPRING_DATASOURCE_PASSWORD: MySQL%4243
    networks:
      - ecommerce-net

  product:
    build: ./product
    ports:
      - "8083:8083"
    depends_on:
      - config-server
      - eureka-server
    environment:
      EUREKA_HOST: eureka-server
      CONFIG_SERVER_HOST: config-server
      REDIS_HOST: redis
      SPRING_DATASOURCE_URL: jdbc:mysql://host.docker.internal:3306/product_db
      SPRING_DATASOURCE_USERNAME: root
      SPRING_DATASOURCE_PASSWORD: MySQL%4243
    networks:
      - ecommerce-net

  cart:
    build: ./cart
    ports:
      - "8084:8084"
    depends_on:
      - config-server
      - eureka-server
    environment:
      EUREKA_HOST: eureka-server
      CONFIG_SERVER_HOST: config-server
      SPRING_DATASOURCE_URL: jdbc:mysql://host.docker.internal:3306/cart_db
      SPRING_DATASOURCE_USERNAME: root
      SPRING_DATASOURCE_PASSWORD: MySQL%4243
    networks:
      - ecommerce-net

  order:
    build: ./order
    ports:
      - "8085:8085"
    depends_on:
      - config-server
      - eureka-server
    environment:
      EUREKA_HOST: eureka-server
      CONFIG_SERVER_HOST: config-server
      SPRING_DATASOURCE_URL: jdbc:mysql://host.docker.internal:3306/order_db
      SPRING_DATASOURCE_USERNAME: root
      SPRING_DATASOURCE_PASSWORD: MySQL%4243
    networks:
      - ecommerce-net

networks:
  ecommerce-net:
    driver: bridge