spring:
  application:
    name: order
  datasource:
    url: jdbc:mysql://localhost:3306/order_db
    username: root
    password: MySQL%4243
  jpa:
    hibernate:
      ddl-auto: update
    properties:
      hibernate:
        dialect: org.hibernate.dialect.MySQLDialect
        show_sql: true
  profiles:
    active: dev

feign:
  client:
    config:
      default:
        loggerLevel: full
        connectTimeout: 5000
        readTimeout: 10000
  httpclient:
    enabled: true
    
server:
  port: 8083

eureka:
  client:
    service-url:
      defaultZone:
        http://localhost:8761/eureka/
    register-with-eureka: true
    fetch-registry: true

management:
  endpoints:
    web:
      exposure:
        include: "*"
  health:
    readiness-state:
      enabled: true
    liveness-state:
      enabled: true
  endpoint:
    shutdown:
      enabled: true
    health:
      probes:
        enabled: true
  info:
    env:
      enabled: true

info:
  app:
    name: "order"
    description: "order microservice"
    version: "1.0.0"

logging:
  level:
    org.springframework.cloud.openfeign: DEBUG
    com.netflix.discovery: DEBUG