spring:
  application:
    name: order
  datasource:
    url: ${SPRING_DATASOURCE_URL:jdbc:mysql://localhost:3306/order_db}
    username: ${DB_USERNAME}
    password: ${DB_PASSWORD}
  jpa:
    hibernate:
      ddl-auto: update
    properties:
      hibernate:
        dialect: org.hibernate.dialect.MySQLDialect
        show_sql: true
  profiles:
    active: dev
  config:
    import: "optional:configserver:http://${CONFIG_SERVER_HOST:localhost}:8888"
  kafka:
    bootstrap-servers: ${KAFKA_HOST:localhost}:9092
    producer:
      key-serializer: org.apache.kafka.common.serialization.StringSerializer
      value-serializer: org.apache.kafka.common.serialization.StringSerializer
      retries: 10
      acks: all
      properties:
        enable.idempotence: true
        max.in.flight.requests.per.connection: 5
        delivery.timeout.ms: 120000
        request.timeout.ms: 30000
        linger.ms: 5
        retry.backoff.ms: 1000
    properties:
      client.id: order-service-producer

server:
  port: 8085

info:
  app:
    name: "order"
    description: "order microservice"
    version: "1.0.0"

management:
  endpoints:
    web:
      exposure:
        include: health,info
  endpoint:
    health:
      show-details: always
  tracing:
    sampling:
      probability: 1.0

logging:
  pattern:
    console: "%d{yyyy-MM-dd'T'HH:mm:ss.SSSXXX} level=%-5p service=${spring.application.name} traceId=%X{traceId:-} spanId=%X{spanId:-} correlationId=%X{correlationId:-} thread=%t logger=%logger{36} msg=%m%n"

resilience4j:
  ratelimiter:
    instances:
      productRateLimiter:
        limitForPeriod: 5
        limitRefreshPeriod: 10s
        timeoutDuration: 1s
      cartRateLimiter:
        limitForPeriod: 5
        limitRefreshPeriod: 10s
        timeoutDuration: 1s

springdoc:
  swagger-ui:
    path: /swagger-ui.html
