spring:
  application:
    name: cart
  datasource:
    url: jdbc:mysql://localhost:3306/cart_db
    username: root
    password: MySQL%4243
  jpa:
    hibernate:
      ddl-auto: update
    properties:
      hibernate:
        dialect: org.hibernate.dialect.MySQLDialect
        show_sql: true
  profiles:
    active: dev
  config:
    import: "optional:configserver:http://localhost:8888"

server:
  port: 8084

info:
  app:
    name: "cart"
    description: "cart microservice"
    version: "1.0.0"